name: Backend CI

on:
  pull_request:
    paths:
      - 'backend/**'  # This will trigger the workflow only if the backend folder is affected
    branches:
      - main  # Run on PRs targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Build the backend
        run: |
          cd backend
          npm run build
        
      - name: Run the build
        run: |
          cd backend
          npm run start
