name: Backend CI

on:
  pull_request:
    paths:
      - 'backend/**'  # This will trigger the workflow only if the backend folder is affected
    branches:
      - main  # Run on PRs targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # Replace with the Node.js version you're using

      - name: Install dependencies
        run: |
          cd backend  # Navigate to your backend folder
          npm install

      - name: Run backend tests
        run: |
          cd backend  # Again, navigate to your backend folder
          npm test  # Replace with your test command (e.g., if you're using Jest, Mocha, etc.)

      - name: Lint the code
        run: |
          cd backend
          npm run lint  # Add your linting command if applicable
